<a href="https://colab.research.google.com/github/elhamod/BA865-2024/blob/main/hands-on/Math_of_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Matrix operations**

**Creating tensors and adding them**

In [1]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[1,3],[3,5]])

In [2]:
B

array([[1, 3],
       [3, 5]])

In [3]:
B.shape

(2, 2)

In [4]:
A

array([[1, 2],
       [3, 4]])

In [5]:
A.shape

(2, 2)

In [6]:
A+B

array([[2, 5],
       [6, 9]])

We can also "broadcast".

In [7]:
C = np.array([3,5])

In [8]:
A+C

array([[4, 7],
       [6, 9]])

**Matrix Dot Product**

In [9]:
A = np.array([[[1, 2, 3, 4], [3, 4, 1 , 3]],[[1, 2, 3, 4], [3, 4, 1 , 3]]])
B = np.array([[3, 4,1], [1 , 3, 1], [1,2, 1], [3,4, 1]])

In [10]:
A.shape

(2, 2, 4)

In [11]:
B.shape

(4, 3)

In [12]:
C = A@B

In [13]:
C

array([[[20, 32, 10],
        [23, 38, 11]],

       [[20, 32, 10],
        [23, 38, 11]]])

In [14]:
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

A neat way to test tensor operations is to create random tensors with specific dimensionalities.

In [15]:
A = np.random.rand(3,4,5, 5, 6, 3)
B = np.random.rand(3, 2)
(A@B).shape

(3, 4, 5, 5, 6, 2)

**Element-wise Multiplication**

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,3],[4,5]])

A*B

In [17]:
C = np.array([1,3])

A*C

array([[ 1,  6],
       [ 3, 12]])

In [18]:
D = np.array([1,3, 5])

A*D

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

**Slicing**

In [19]:
A = np.array([[1,2],[3,4]])

A[:, 1]

array([2, 4])

In [20]:
B = np.array([[[1,2, 1],[3,4, 2]], [[1,2, 2],[3,4, 1]]])

B.shape

(2, 2, 3)

In [21]:
B[:, 1, :].shape

(2, 3)

In [22]:
B[:, :, 1].shape

(2, 2)

In [23]:
B[:, :, 0:2].shape

(2, 2, 2)

##What does a linear transformation look like?

Let's draw a line

In [24]:
import numpy as np
import matplotlib.pyplot as plt

# Define the start and end points
start_point = np.array([-1, -2])
end_point = np.array([5, 8])

# Number of points (including the start and end points)
num_points = 10

# Create an array of equally spaced points
line = np.linspace(start_point, end_point, num_points)

In [25]:
# Plot a set of points and their transformation
def plot_transformation(points, transformed_points):
  # Plotting
  plt.figure(figsize=(8, 8))
  plt.plot(points[:, 0], points[:, 1], 'b-', label='Original Points')
  plt.plot(transformed_points[:, 0], transformed_points[:, 1], 'r-', label='Transformed Points')

  plt.scatter(points[:, 0], points[:, 1], marker='o', color='b')
  plt.scatter(transformed_points[:, 0], transformed_points[:, 1], marker='o', color='r')

  plt.xlabel('X-axis')
  plt.ylabel('Y-axis')
  plt.title('Transformation of Points')
  plt.legend()
  plt.grid(True)
  plt.axis('equal')
  plt.show()

Transform and plot!

**How About Non-linearities?**

##Gradients


Let's pick a function and explore its gradient

In [59]:
import torch

def func_torch(x, y):
  return (torch.sin(x) * torch.sin(y))

# Create a 2D array of equally spaced points
x = np.linspace(0, 5, 500)
y = np.linspace(0, 5, 500)
X, Y = np.meshgrid(x, y)
f_xy = func_torch(torch.from_numpy(X), torch.from_numpy(Y))

Let's do gradient descent with the help of **autodiff** from  *pytorch*.

In [54]:
starting_point = np.array([1.6, 1.6])
alpha = 0.1
num_of_epochs = 60

Let's plot

In [57]:
import plotly.graph_objects as go

def plot_gradient_descent(points):
  # Create a surface plot using Plotly
  fig = go.Figure(data=[go.Surface(z=f_xy, x=X, y=Y)])

  # Update layout and axis labels
  fig.update_layout(title='Surface Plot',
                    scene=dict(xaxis_title='X',
                              yaxis_title='Y',
                              zaxis_title='f(X, Y)'))

  # Add a scatter plot (set of points) to the figure
  fig.add_trace(go.Scatter3d(x=points[:,0], y=points[:,1], z=points[:,2],
                            mode='markers', marker=dict(size=5, color='red')))


  # Show the plot
  fig.show()

In [ ]:
plot_gradient_descent(points.detach().numpy())

**MSE and MAE**

In [ ]:
import torch
import torch.nn.functional as F



**Softmax and Cross Entropy**

In [ ]:
import torch
import torch.nn as nn



Another way

In [ ]:
import torch
import torch.nn.functional as F



Let's play with this a bit

In [44]:
import numpy as np
# from sklearn.metrics import log_loss
import ipywidgets as widgets
from IPython.display import display



In [45]:
# Create sliders for each logit
logit1_slider = widgets.FloatSlider(value=0.0, min=-10.0, max=10.0, step=0.1, description='Logit 1:')
logit2_slider = widgets.FloatSlider(value=0.0, min=-10.0, max=10.0, step=0.1, description='Logit 2:')
logit3_slider = widgets.FloatSlider(value=0.0, min=-10.0, max=10.0, step=0.1, description='Logit 3:')

In [ ]:
# Display the sliders and the result
ui = widgets.VBox([logit1_slider, logit2_slider, logit3_slider])
out = widgets.interactive_output(calculate_loss, {'logit1': logit1_slider, 'logit2': logit2_slider, 'logit3': logit3_slider})
display(ui, out)